
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/ktp?useUnicode=true&usesSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789g
server:
  servlet:
    session:
      timeout: 10s
